site_name: PySAC
site_url: http://jkmacc-lanl.github.io/pysac/
repo_url: https://github.com/jkmacc-LANL/pysac
site_description: Python interface to the Seismic Analysis Code (SAC) file format.
theme: readthedocs
use_directory_urls: false
markdown_extensions:
    - toc:
        permalink: True
docs_dir: 'source'
site_dir: 'site'
pages:
- Introduction: 'index.md'
- Package: 'package.md'
- About:
    - 'License': 'license.md'
    - 'ObsPy': 'obspy.md'
